import { Metadata } from "next"
import Link from "next/link"
import { ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"

export const metadata: Metadata = {
  title: "Terms of Service - VoiceSync",
  description: "VoiceSync Terms of Service - Rules and guidelines for using our platform.",
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container max-w-4xl mx-auto py-8">
        <div className="mb-8">
          <Button variant="ghost" asChild className="mb-4">
            <Link href="/" className="flex items-center gap-2">
              <ArrowLeft className="h-4 w-4" />
              Back to Home
            </Link>
          </Button>
          <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
          <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
        </div>

        <div className="prose prose-gray dark:prose-invert max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing and using VoiceSync, you accept and agree to be bound by the terms and provision 
              of this agreement. If you do not agree to abide by the above, please do not use this service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">2. Service Description</h2>
            <p className="text-muted-foreground leading-relaxed">
              VoiceSync is an AI-powered audio translation and dubbing platform that converts audio content 
              from one language to another using advanced machine learning technologies including OpenAI Whisper, 
              DeepSeek translation models, and XTTS-v2 text-to-speech synthesis.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">3. Acceptable Use</h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-medium mb-2">Permitted Uses</h3>
                <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                  <li>Personal and commercial audio translation projects</li>
                  <li>Educational content localization</li>
                  <li>Business presentations and marketing materials</li>
                  <li>Content creation for multiple language audiences</li>
                </ul>
              </div>
              <div>
                <h3 className="text-lg font-medium mb-2">Prohibited Uses</h3>
                <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                  <li>Uploading copyrighted content without proper authorization</li>
                  <li>Creating deepfakes or misleading audio content</li>
                  <li>Processing content that violates applicable laws</li>
                  <li>Uploading malicious files or attempting to compromise our systems</li>
                  <li>Using the service for harassment, hate speech, or illegal activities</li>
                </ul>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">4. Content Ownership and Rights</h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-medium mb-2">Your Content</h3>
                <p className="text-muted-foreground leading-relaxed">
                  You retain all rights to the original audio content you upload. By using our service, 
                  you grant us a temporary license to process your content for the sole purpose of providing 
                  translation and dubbing services.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium mb-2">Generated Content</h3>
                <p className="text-muted-foreground leading-relaxed">
                  You own the translated and dubbed content generated by our service. However, you are 
                  responsible for ensuring that your use of both original and generated content complies 
                  with applicable copyright and intellectual property laws.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">5. Service Availability</h2>
            <p className="text-muted-foreground leading-relaxed">
              We strive to maintain high service availability but cannot guarantee uninterrupted access. 
              We may temporarily suspend the service for maintenance, updates, or due to circumstances 
              beyond our control. We will provide reasonable notice when possible.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">6. Quality and Accuracy</h2>
            <p className="text-muted-foreground leading-relaxed">
              While we use advanced AI technologies to provide high-quality translations and dubbing, 
              we cannot guarantee 100% accuracy. The quality of output depends on various factors including 
              audio quality, language complexity, and technical limitations of AI models. Users should 
              review and verify generated content before use.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">7. Privacy and Data Protection</h2>
            <p className="text-muted-foreground leading-relaxed">
              Your privacy is important to us. Please review our Privacy Policy to understand how we 
              collect, use, and protect your data. By using our service, you consent to the data 
              practices described in our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">8. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              VoiceSync shall not be liable for any indirect, incidental, special, consequential, or 
              punitive damages, including without limitation, loss of profits, data, use, goodwill, 
              or other intangible losses, resulting from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">9. Indemnification</h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree to defend, indemnify, and hold harmless VoiceSync from and against any claims, 
              damages, obligations, losses, liabilities, costs, or debt, and expenses (including attorney's fees) 
              arising from your use of the service or violation of these terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">10. Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may terminate or suspend your access to the service immediately, without prior notice 
              or liability, for any reason whatsoever, including without limitation if you breach the Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">11. Changes to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to modify or replace these Terms at any time. If a revision is material, 
              we will try to provide at least 30 days notice prior to any new terms taking effect.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">12. Governing Law</h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms shall be interpreted and governed by the laws of the jurisdiction in which 
              VoiceSync operates, without regard to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">13. Contact Information</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have any questions about these Terms of Service, please contact us at:
            </p>
            <div className="mt-4 p-4 bg-muted rounded-lg">
              <p className="font-medium">Email: VoiceSync@like228.com</p>
              <p className="text-sm text-muted-foreground mt-1">
                We will respond to your inquiry within 48 hours.
              </p>
            </div>
          </section>
        </div>
      </div>
    </div>
  )
} 